alter table SURVEY_SELECTED_ANSWER add constraint FK_SURVEY_SELECTED_ANSWER_QUESTION_ID foreign key (QUESTION_ID) references SURVEY_QUESTION(ID);
alter table SURVEY_SELECTED_ANSWER add constraint FK_SURVEY_SELECTED_ANSWER_ANSWER_ID foreign key (ANSWER_ID) references SURVEY_POSSIBLE_ANSWER(ID);
alter table SURVEY_SELECTED_ANSWER add constraint FK_SURVEY_SELECTED_ANSWER_FILLED_SURVEY_ID foreign key (FILLED_SURVEY_ID) references SURVEY_FILLED_SURVEY(ID);
create index IDX_SURVEY_SELECTED_ANSWER_ANSWER on SURVEY_SELECTED_ANSWER (ANSWER_ID);
create index IDX_SURVEY_SELECTED_ANSWER_QUESTION on SURVEY_SELECTED_ANSWER (QUESTION_ID);
create index IDX_SURVEY_SELECTED_ANSWER_FILLED_SURVEY on SURVEY_SELECTED_ANSWER (FILLED_SURVEY_ID);
