alter table SURVEY_QUESTION add constraint FK_SURVEY_QUESTION_CATEGORY foreign key (CATEGORY_ID) references SURVEY_QUESTION_CATEGORY(ID);
create index IDX_SURVEY_QUESTION_CATEGORY on SURVEY_QUESTION (CATEGORY_ID);
